import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('shell.css', () => {
  const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')

  it('defines desktop grid areas and golden-ratio columns/rows', () => {
    expect(css).toContain("grid-template-areas:")
    expect(css).toContain("'header header'")
    expect(css).toContain("'main navigation'")
    expect(css).not.toContain("'main side-panel'")
    expect(css).toContain("'footer footer'")
    expect(css).not.toContain("'dock dock'")
    expect(css).toContain('minmax(0, 1.618fr)')
    expect(css).toContain('minmax(280px, 1fr)')
  })

  it('keeps the shell at viewport height and scrolls content internally', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-shell\s*\{[^}]*height:\s*100dvh/)
    expect(css).toMatch(/\.syn-main\s*\{[^}]*overflow-y:\s*auto/)
    const idx = css.indexOf('@media (max-width: 768px)')
    expect(idx).toBeGreaterThan(-1)
    const mobile = css.slice(idx)
    expect(mobile).toMatch(/\.syn-shell\s*\{[^}]*height:\s*auto/)
    expect(mobile).toMatch(/\.syn-header\s*\{[^}]*position:\s*sticky/)
    expect(mobile).toMatch(/\.syn-site-footer\s*\{[^}]*position:\s*sticky/)
  })

  it('resets the body margin so the bars hug the viewport edges', () => {
    expect(css).toMatch(/body\s*\{[^}]*margin:\s*0/)
  })

  it('draws the reference left/right borders along the content grid', () => {
    expect(css).toMatch(/\.syn-shell\s*\{[^}]*border-left:\s*var\(--syn-border-strong\)/)
    expect(css).toMatch(/\.syn-shell\s*\{[^}]*border-right:\s*var\(--syn-border-strong\)/)
  })

  it('lays the footer bar out like the reference bottom bar with the language switcher inside', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*display:\s*flex/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*align-items:\s*center/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*justify-content:\s*space-between/)
    expect(css).not.toMatch(/\.syn-language\s*\{[^}]*position:\s*fixed/)
    expect(css).toMatch(/\.syn-language\s*\{[^}]*position:\s*relative/)
    expect(css).toMatch(/\.syn-language\s*\{[^}]*transform:\s*translateY\(-3px\)/)
  })

  it('renders the social links as chips in the nav side-panel', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).not.toMatch(/\.syn-social-links\s*\{[^}]*position:\s*fixed/)
    expect(css).not.toMatch(/\.syn-shell__dock/)
    expect(css).toMatch(/\.syn-social-links\s*\{[^}]*gap:\s*var\(--syn-dock-gap\)\s*18px/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*flex-direction:\s*column/)
    expect(css).toMatch(/\.syn-link-cloud__link\s*\{[^}]*font-size:\s*16px/)
    expect(css).toMatch(/\.syn-link-cloud__link\s*\{[^}]*text-decoration:\s*underline/)
    expect(css).not.toMatch(/\.syn-link-cloud__link\s*\{[^}]*background:/)
    expect(css).toMatch(/\.syn-link-cloud__divider\s*\{[^}]*width:\s*120px/)
    expect(css).toMatch(/\.syn-link-cloud__divider\s*\{[^}]*height:\s*1px/)
    expect(css).toMatch(/\.syn-navigation__side-panel:has\(\.syn-link-cloud\)\s*\{[^}]*grid-template-rows:\s*1fr\s*auto\s*1fr/)
    expect(css).toMatch(/\.syn-link-cloud\s*\{[^}]*display:\s*contents/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*padding:\s*20px/)
  })

  it('styles the home logo with reference .logo/.logo-sub classes and full-width title cell', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-main\s*>\s*\.cell\s*\{[^}]*margin-inline:\s*auto/)
    expect(css).toMatch(/\.syn-main:has\(\.syn-home-logo\)\s*\{[^}]*padding:\s*24px/)
    expect(css).toMatch(/\.syn-main:has\(\.syn-home-logo\)\s*>\s*\.cell\s*\{[^}]*max-width:\s*none/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*--syn-dock-control-size:\s*28px/)
    expect(css).toMatch(/\.syn-navigation__side-panel:has\(\.syn-link-cloud\)\s*\.syn-social-links\s*\{[^}]*align-self:\s*end/)
    expect(css).toMatch(/\.syn-navigation__side-panel:has\(\.syn-link-cloud\)\s*\.syn-link-cloud__list\s*\{[^}]*align-self:\s*start/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*font-size:\s*clamp\(48px,\s*9vw,\s*96px\)/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*font-weight:\s*900/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*font-size:\s*14px/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*text-transform:\s*uppercase/)
    expect(css).toMatch(/\.syn-main:has\(\.syn-home-logo\)[^{]*\.[^}]*max-width:\s*none/)
    expect(css).toMatch(/\.syn-main:has\(\.syn-home-logo\)\s*>\s*\.cell\s*\{[^}]*justify-content:\s*center/)
    expect(css).toMatch(/\.syn-main:has\(\.syn-home-logo\)\s*>\s*\.cell\s*\{[^}]*display:\s*flex/)
    expect(css).not.toMatch(/\.syn-home-logo\s*\{[^}]*min-height:/)
    expect(css).toMatch(/\.syn-formatter--home-logo\s*\{[^}]*display:\s*contents/)
  })

  it('uses the mobile breakpoint at 768px and keeps the dock control tokens', () => {
    expect(css).toContain('@media (max-width: 768px)')
    expect(css).toContain('var(--syn-dock-gap)')
    expect(css).toContain('var(--syn-dock-control-size)')
    expect(css).not.toContain('var(--syn-dock-content-clearance)')
  })

  it('keeps the bars at reference height (no p margins, in-bar controls shrink)', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-topbar-text\s*\{[^}]*margin:\s*0/)
    expect(css).toMatch(/\.syn-topbar-text\s*\{[^}]*font-family:\s*var\(--syn-font-display\)/)
    expect(css).toMatch(/\.syn-footbar-text\s*\{[^}]*margin:\s*0/)
    expect(css).toMatch(/\.syn-footbar-text\s*\{[^}]*font-family:\s*var\(--syn-font-display\)/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*font-family:\s*var\(--syn-font-display\)/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*font-family:\s*var\(--syn-font-display\)/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*font-family:\s*var\(--syn-font-display\)/)
    expect(css).toMatch(/\.syn-header\s*\{[^}]*--syn-dock-control-size:\s*20px/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*--syn-dock-control-size:\s*20px/)
    expect(css).not.toContain('@media (max-width: 360px)')
  })

  it('keeps the footer controls visible while the drawer is open', () => {
    expect(css).not.toMatch(/\.syn-shell--drawer-open[\s\S]*\.syn-social-links/)
    expect(css).not.toMatch(/\.syn-shell--drawer-open[\s\S]*\.syn-language/)
  })

  it('styles header and footer as reference bars', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-header\s*\{[^}]*background:\s*var\(--syn-bar-bg\)/)
    expect(css).toMatch(/\.syn-header\s*\{[^}]*color:\s*var\(--syn-bar-fg\)/)
    expect(css).toMatch(/\.syn-header\s*\{[^}]*letter-spacing:\s*2px/)
    expect(css).toMatch(/\.syn-header\s*\{[^}]*padding:\s*10px 16px/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*background:\s*var\(--syn-bar-bg\)/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*color:\s*var\(--syn-bar-fg\)/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*border-top:\s*var\(--syn-border-strong\)/)
  })

  it('styles the theme toggle like the reference theme-option', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-bar-chip\s*\{[^}]*background:\s*var\(--syn-bar-fg\)/)
    expect(css).toMatch(/\.syn-bar-chip\s*\{[^}]*color:\s*var\(--syn-bar-bg\)/)
    expect(css).toMatch(/\.syn-bar-chip\s*\{[^}]*border:\s*var\(--syn-border-strong\)/)
    expect(css).toMatch(/\.syn-theme-mode__button\s*\{[^}]*font-size:\s*12px/)
    expect(css).toMatch(/\.syn-theme-mode__button\s*\{[^}]*padding:\s*0 8px/)
    expect(css).toMatch(/\.syn-theme-mode__button:hover[^{]*\{[^}]*text-decoration:\s*underline/)
    expect(css).toMatch(/\.syn-language__toggle\s*\{[^}]*max-width:\s*40vw/)
    expect(css).not.toMatch(/\.syn-language__toggle\s*\{[^}]*background:/)
  })

  it('renders the navigation column as a deco link-panel column', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-navigation\s*\{[^}]*grid-template-rows:\s*minmax\(0,\s*1\.618fr\)\s*minmax\(0,\s*1fr\)/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*align-items:\s*center/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*justify-content:\s*center/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*border-top:\s*var\(--syn-border-strong\)/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*padding:\s*20px/)
    expect(css).not.toMatch(/\.syn-nav-drawer__side-panel/)
    expect(css).not.toMatch(/\.syn-side-panel/)
    expect(css).toMatch(/\.syn-navigation\s*\{[^}]*background:\s*var\(--syn-deco-bg\)/)
    expect(css).toMatch(/\.syn-navigation\s*\{[^}]*color:\s*var\(--syn-deco-label-fg\)/)
    expect(css).toMatch(/\.syn-navigation\s*\{[^}]*display:\s*grid/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*display:\s*flex/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*flex:\s*1/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*justify-content:\s*space-between/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*padding:\s*20px 24px/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*font-size:\s*13px/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*letter-spacing:\s*2px/)
    expect(css).toMatch(/\.syn-navigation__link\s*\{[^}]*text-decoration:\s*none/)
    expect(css).toMatch(/\.syn-navigation__label\s*\{[^}]*margin-inline-start:\s*auto/)
    expect(css).toMatch(/\.syn-navigation__label\s*\{[^}]*text-align:\s*right/)
    expect(css).toMatch(/\.syn-navigation__mark-icon\s*\{[^}]*width:\s*36px/)
    expect(css).toMatch(/\.syn-navigation__mark-icon\s*\{[^}]*height:\s*36px/)
    expect(css).toMatch(/\.syn-navigation__link:hover[^{]*\{[^}]*background:\s*var\(--syn-deco-symbol-bg\)/)
    expect(css).toMatch(/\.syn-navigation__link:hover[^{]*\{[^}]*color:\s*var\(--syn-deco-bg\)/)
    expect(css).toMatch(/\.syn-navigation__link:focus-visible[^{]*\{[^}]*background:\s*var\(--syn-deco-symbol-bg\)/)
    expect(css).toMatch(/\.syn-navigation__link:focus-visible[^{]*\{[^}]*color:\s*var\(--syn-deco-bg\)/)
    expect(css).toMatch(/\.syn-navigation__item\s*\+\s*\.syn-navigation__item\s*\{[^}]*border-block-start:\s*var\(--syn-border-strong\)/)
  })

  it('applies reference display metrics to the home logo', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-home-logo\s*\{[^}]*text-align:\s*right/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*font-size:\s*clamp\(48px,\s*9vw,\s*96px\)/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*font-weight:\s*900/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*line-height:\s*0\.9/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*letter-spacing:\s*-2px/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*font-size:\s*14px/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*letter-spacing:\s*4px/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*text-transform:\s*uppercase/)
    expect(css).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*color:\s*var\(--syn-sub-title-fg\)/)
  })

  it('aligns dock and language controls with reference letter-spacing and hover', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-social-links__link:hover[^{]*\s*\.syn-social-links__icon[^{]*\{[^}]*opacity:\s*0\.6/)
    expect(css).not.toMatch(/\.syn-social-links__link:hover[^{]*\{[^}]*background:\s*var\(--syn-deco-symbol-bg\)/)
    expect(css).toMatch(/\.syn-navigation__side-panel\s*\{[^}]*background:\s*var\(--syn-bg\)/)
    expect(css).toMatch(/\.syn-nav-drawer\s*\.syn-navigation__side-panel\s*\{[^}]*background:\s*transparent/)
    expect(css).toMatch(/\.syn-language__list\s*\{[^}]*bottom:\s*40px/)
    expect(css).toMatch(/\.syn-language__option\[aria-selected='true'\]\s*\{[^}]*background:\s*var\(--syn-bg\)/)
    expect(css).toMatch(/\.syn-language__option\[aria-selected='true'\]\s*\{[^}]*color:\s*var\(--syn-fg\)/)
    expect(css).toMatch(/\.syn-language__option\[aria-selected='false'\]\s*\{[^}]*background:\s*var\(--syn-fg\)/)
    expect(css).toMatch(/\.syn-language__option\[aria-selected='false'\]\s*\{[^}]*color:\s*var\(--syn-bg\)/)
    expect(css).toMatch(/\.syn-site-footer\s*\{[^}]*z-index:\s*50/)
    expect(css).not.toMatch(/\.syn-language\s*\{[^}]*z-index:/)
    expect(css).toMatch(/\.syn-language__toggle\s*\{[^}]*max-width:\s*40vw/)
    expect(css).toMatch(/\.syn-language__toggle\s*\{[^}]*font-size:\s*12px/)
    expect(css).toMatch(/\.syn-language__option\s*\{[^}]*letter-spacing:\s*1px/)
    expect(css).toMatch(/\.syn-language__toggle:hover[^{]*\{[^}]*text-decoration:\s*underline/)
    expect(css).not.toMatch(/\.syn-nav-drawer__close/)
    expect(css).not.toMatch(/\.syn-nav-drawer__bar/)
  })

  it('lays the nav drawer over the main area so bars and shell borders stay visible', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-main\s*\{[^}]*position:\s*relative/)
    expect(css).toMatch(/\.syn-nav-drawer\s*\{[^}]*position:\s*absolute/)
    expect(css).toMatch(/\.syn-nav-drawer\s*\{[^}]*inset:\s*0/)
    // The drawer stays rendered so the fade can animate (visibility,
    // not display, toggles; the header icon morphs into a close icon).
    expect(css).toMatch(/\.syn-nav-drawer\s*\{[^}]*visibility:\s*hidden/)
    expect(css).toMatch(/\.syn-nav-drawer\s*\{[^}]*opacity:\s*0/)
    expect(css).toMatch(/\.syn-shell--drawer-open\s*\.syn-nav-drawer\s*\{[^}]*opacity:\s*1/)
    expect(css).toMatch(/\.syn-header__menu-icon--active\s*line:nth-child\(1\)\s*\{[^}]*rotate\(45deg\)/)
    expect(css).toMatch(/\.syn-header__menu-icon--active\s*line:nth-child\(3\)\s*\{[^}]*rotate\(-45deg\)/)
  })

  it('styles the hamburger as a plain currentColor icon', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    expect(css).toMatch(/\.syn-header__menu\s*\{[^}]*background:\s*transparent/)
    expect(css).toMatch(/\.syn-header__menu\s*\{[^}]*border:\s*0/)
    expect(css).toMatch(/\.syn-header__menu\s*\{[^}]*color:\s*var\(--syn-bar-fg\)/)
  })

  it('adds the reference 640px mobile breakpoint', () => {
    const css = readFileSync(resolve('src/client/styles/shell.css'), 'utf8')
    const idx = css.indexOf('@media (max-width: 640px)')
    expect(idx).toBeGreaterThan(-1)
    const mobile = css.slice(idx)
    expect(mobile).toMatch(/\.syn-header\s*\{[^}]*font-size:\s*11px/)
    expect(mobile).toMatch(/\.syn-site-footer\s*\{[^}]*font-size:\s*11px/)
    expect(mobile).toMatch(/\.syn-home-logo\s*\.logo\s*\{[^}]*font-size:\s*52px/)
    expect(mobile).toMatch(/\.syn-navigation__link\s*\{[^}]*padding:\s*14px 16px/)
    expect(mobile).toMatch(/\.syn-home-logo\s*\.logo-sub\s*\{[^}]*font-size:\s*10px/)
  })
})
